POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "names": "Andres Felipe",
  "lastName": "Ramirez",
  "identification": "1234567890",
  "email": "andres@gmail.com",
  "password": "andres1234",
  "phoneNumber": "3102162732",
  "birthday": "2007-06-05"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin1234"
}

###
GET http://localhost:8080/api/v1/seller/
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6W10sInN1YiI6IjEwOTQyNDc3NDUiLCJpYXQiOjE3NzYzMDMyOTIsImV4cCI6MTc3NjMwMzMyMn0.tlLj1QZN_eEZysOLK7sEHq3yL2E2LvJTHApbHKFhSCesbQl1FN7ksw3GeO0HJ07E
Content-Type: application/json

###
GET http://localhost:8080/api/v1/buyer/
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6W10sInN1YiI6IjEwOTQyNDc3NDUiLCJpYXQiOjE3NzYzMDMzMTcsImV4cCI6MTc3NjMwMzM0N30.99lvhbsRzoCW8G4iB8Z61fRhd64TY-5u-gbcVC_wKqq38DjfbvPoFKOPZTwG73rk
Content-Type: application/json